export const PROJECT_DATA = [
  {
    position: "left",
    link: "https://raw.githubusercontent.com/tusharkhatri434/my-project-assets/refs/heads/master/snake-game.png",
    title: "Snake-Game",
    date: "(march 2024) 📲",
    desc: "A classic Snake game where the snake's speed increases as it consumes food.",
    tags: ["Html", "CSS3", "JavaScript"],
    live: "https://snake-game-tusharchaudhary.netlify.app/",
    github: "https://github.com/Tushar9643426880/Snake-Game",
  },
  {
    position: "right",
    link: "https://raw.githubusercontent.com/tusharkhatri434/my-project-assets/refs/heads/master/tic-tac-toe.png",
    title: "Tic-toe-game",
    date: "(march 2024) 📲",
    desc: "Created a two-player Tic-Tac-Toe game that checks for wins dynamically and notifies players when one of them wins",
    tags: ["Html", "CSS3", "JavaScript"],
    live: "https://tic-tac-toe-tusharchaudhary.netlify.app/",
    github: "https://github.com/Tushar9643426880/tic-tac-toe",
  },
  {
    position: "left",
    link: "https://raw.githubusercontent.com/tusharkhatri434/my-project-assets/master/p4.png",
    title: "To-DO App",
    date: "(FEBRUARY 2024) 📲",
    desc: "My to-do app, designed with pure HTML, CSS, and JS, offers full CRUD functionality and responsive design for seamless task management.",
    tags: ["Html", "CSS3", "JavaScript"],
    live: "https://to-do-app-tusharchaudhary.netlify.app/",
    github: "https://github.com/Tushar9643426880/To-do-list",
  },
  {
    position: "right",
    link: "https://raw.githubusercontent.com/tusharkhatri434/my-project-assets/master/p5.png",
    title: "Drum Sticks",
    date: "(October 2023) 🥁",
    desc: "Developed an interactive drum kit that plays different sounds when users click on various drum parts.",
    tags: ["Html", "CSS3", "JavaScript"],
    live: "https://playing-drum-tusharchaudhary.netlify.app/",
    github: "https://github.com/Tushar9643426880/playing-drum",
  },
];
